server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yggauth
    username: ygg
    password: ygg
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

auth:
  access-token-ttl: 24h
  join-ttl: 60s
  pepper: "CHANGE_ME_RANDOM_LONG_STRING"
  bcrypt-strength: 12

ygg:
  base-url: "http://localhost:8080"
  yggdrasil:
    api: "http://localhost:8080/authserver"

  meta:
    implementation-name: "Yggdrasil API (Local)"
    implementation-version: "dev"
    server-name: "LocalDev"
    links:
      homepage: "http://localhost:8080"
      register: "http://localhost:8080/register"
    feature:
      enable-profile-key: false

  skin-domains:
    - "localhost"
    - "127.0.0.1"
    - "textures.minecraft.net"

  signature-public-key:
  signature-private-key:

  services:
    attributes:
      online-chat: true
      multiplayer-server: true
      multiplayer-realms: true
      telemetry: false
    blocklist-enabled: true
    profile-keys:
      enabled: false
      ttl: 48h
      signing-private-key:

  textures:
    serve-local: true
    storage-dir: "./build/textures"
    base-url: "http://localhost:8080/textures"
    sign: false
